- name: nginx install and run
  hosts: all
  become: yes #takes sudo access
  var_files:
    - /var/expense/credentials_mysql.yaml
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
