- name: remove the existing {{app_location}} directory
  ansible.builtin.file:
    name: "{{app_location}}"
    state: absent
  ignore_errors: true

- name: create {{app_location}} directory
  ansible.builtin.file:
    name: "{{app_location}}"
    state: directory

- name: download the {{ component }} code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{app_location}}"
    remote_src: yes
